# Generated by Django 4.1.4 on 2023-01-17 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserdetailsModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='Name')),
                ('user_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('user_password', models.CharField(max_length=100, verbose_name='Password')),
                ('user_contact', models.BigIntegerField(verbose_name='contact')),
                ('user_city', models.CharField(max_length=100, verbose_name='city')),
                ('user_photo', models.FileField(upload_to='media', verbose_name='Photo')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
                ('user_status', models.CharField(default='pending', max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
