# Generated by Django 4.1.4 on 2023-01-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('vid_id', models.AutoField(primary_key=True, serialize=False)),
                ('vid_url', models.CharField(max_length=150, null=True)),
                ('vid_url_id', models.CharField(max_length=100, null=True)),
                ('vid_sentiment', models.CharField(max_length=150, null=True)),
                ('datetime_searched', models.DateTimeField(auto_now=True)),
                ('search_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search', to='mainapp.userdetailsmodel')),
            ],
            options={
                'db_table': 'video_details',
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=500, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('sentiment', models.CharField(max_length=50, null=True)),
                ('datetime_reviewed', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='mainapp.userdetailsmodel')),
            ],
            options={
                'db_table': 'user_feedbacks',
            },
        ),
    ]
